version: '3.8'

services:
  defensive-system:
    build: .
    container_name: defensive-cybersecurity
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - REGION=us-east-1
      - LOG_LEVEL=INFO
      - DEFENSIVE_MODE=true
      - MONITORING_ENABLED=true
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./configs:/app/configs:ro
    networks:
      - defensive-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4G'
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "python3", "health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs

  monitoring:
    image: prom/prometheus:latest
    container_name: defensive-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - defensive-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

networks:
  defensive-network:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
